### ISSUE TITLE
Question about including the template url in stub file?

### ISSUE THREAD

**Issue by jauyzed** [widdix/learn-cloudformation#1]
Hello,

I like your simple explanation of nested templates. Was wondering if we need to include the URL something like this below or just URL would work? 

"TemplateURL": "http://s3/template1",
"TemplateURL": "http://s3/template2"        

I have more complicated template with over 3000 lines of code, we are mostly using all the functions available. Would the functions(ref, findinmap) work normally?

Thanks

**Comment by andreaswittig** [comment]
Hi @jauyzed,

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-templateurl answers your question regarding the TemplateURL.

Functions Ref and FindInMap are working only inside a template not across templates. You are probably looking for http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-crossstackref.html.

Andreas

**Comment by jauyzed** [comment]
Hi Andreas,

I appreciate your reply. This solution you have provided for the lab is not going to work. 

From your template: 

```
"Resources": {
        // add stacks
        // https://s3-eu-west-1.amazonaws.com/learn-cloudformation/lab7-nested-stacks/ec2-stack.json
        // https://s3-eu-west-1.amazonaws.com/learn-cloudformation/lab7-nested-stacks/s3-stack.json

    }
```

Im not sure if you can include a template's raw url or multiple URLS's inside resources section like above. Editor complains about template not well formed with json errors. 

-Jauyzed

**Comment by andreaswittig** [comment]
Please have a look at the sample solution: https://github.com/widdix/learn-cloudformation/blob/master/lab7-nested-stacks/sample-solution.json

Do you have more questions? I'd be happy answering them during a codementor Session: https://www.codementor.io/andreaswittig

I have created an online course about CloudFormation as well: http://shrsl.com/?c0qb
